[package]
name = "ipa-sounds"
version = "0.3.2"
edition = "2021"
description = "IPA sounds"
authors = ["Мира Лущаева <miralushch@gmail.com>"]
license = "MIT"

[dependencies]
value-enum = { version = "0.4.0", git = "https://github.com/miralushch/value-enum" }
